### ISSUE TITLE
Creating an unsigned image with imgtool requires using the "sign" subcommand

### ISSUE THREAD

**Issue by SebastianBoe** [runtimeco/mcuboot#240]
Creating an unsigned image with imgtool requires using the "sign" subcommand. Either a new subcmd needs to be added, or the "sign" subcommand needs to renamed to "create".

**Comment by utzig** [comment]
Using `create` seems like a good idea!

**Comment by d3zd3z** [comment]
When you "sign" without using a key, it is still putting a sha hash at the end. I'm not sure if `create` really captures this either, but I'm not sure what the best word would be.

If we did add another command, it should probably just be an alias, since sign does really make sense for the cases where we sign the image.

What do you think of #251 as a solution to this?

**Comment by SebastianBoe** [comment]
"What do you think of #251 as a solution to this?"

Review feedback given in #251.

**Comment by aditihilbert** [comment]
how about a flag like -n (no sign, hash only)?

**Comment by d3zd3z** [comment]
I don't think it would be helpful to have a flag to indicate no signature. If you give a key, it will be signed, if you don't give a key, it won't be signed. We just have to make the description clear enough. Any reviews on #251 would be appreciated.
